### ISSUE TITLE
[Migration] Typescript

### ISSUE THREAD

**Issue by hyochan** [dooboolab/talktalk-node#29]
Migration to `typescript`.

**Comment by cometkim** [comment]
FYI: We'll lose the optional chaining syntax in this case

**Comment by hyochan** [comment]
Thanks for the info! We can use other ts-util like [ts-optchain](https://www.npmjs.com/package/ts-optchain).

**Comment by cometkim** [comment]
This task has done in #28. will ready to use TypeScript right after it merged
