### ISSUE TITLE
We need local setup guidance in readme.

### ISSUE THREAD

**Issue by hyochan** [dooboolab/talktalk-node#8]
As we've discussed earlier in meetup, we need local configuration in the readme. Especially for setting up the local database to `docker-compose`. I can change this readme but I want someone else to contribute on this to give self warm up.

**Comment by hyochans** [comment]
@bumjoo.lee @정준명 @geoseong Anyone of you can start with this.

**Comment by geoseong** [comment]
> @bumjoo.lee @정준명 @geoseong Anyone of you can start with this.

@hyochan, I configured and created Pull Request.

**Comment by hyochan** [comment]
@geoseong Yeah. Please check my review.

**Comment by geoseong** [comment]
@hyochan where can I check your review?

**Comment by hyochan** [comment]
Check PR #10 😁
